// Extracted and adapted from RedCoconut — CSV to SQL INSERT generator

export type SqlDialect = 'mysql' | 'postgresql' | 'sqlite' | 'sqlserver';

interface ColumnConfig {
  sourceIndex: number;
  sourceName: string;
  targetName: string;
  include: boolean;
}

interface GeneratorOptions {
  dialect: SqlDialect;
  tableName: string;
  schemaName: string;
  rowsPerInsert: number;
  quoteIdentifiers: boolean;
  trimStrings: boolean;
  emptyStringAsNull: boolean;
}

function chunkArray<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));
  return chunks;
}

function normalizeId(value: string): string {
  return value.trim().replace(/\s+/g, '_');
}

function quoteId(id: string, dialect: SqlDialect, quote: boolean): string {
  const v = normalizeId(id);
  if (!v || !quote) return v;
  if (dialect === 'mysql' || dialect === 'sqlite') return `\`${v.replaceAll('`', '``')}\``;
  if (dialect === 'sqlserver') return `[${v.replaceAll(']', ']]')}]`;
  return `"${v.replaceAll('"', '""')}"`;
}

function toSqlLiteral(value: string, opts: GeneratorOptions): string {
  if (value === null || value === undefined) return 'NULL';
  let s = String(value);
  if (opts.trimStrings) s = s.trim();
  if (opts.emptyStringAsNull && s.length === 0) return 'NULL';
  const lower = s.toLowerCase();
  if (lower === 'null' || lower === 'nil' || lower === 'n/a') return 'NULL';
  if (lower === 'true' || lower === 'false') {
    if (opts.dialect === 'postgresql') return lower === 'true' ? 'TRUE' : 'FALSE';
    return lower === 'true' ? '1' : '0';
  }
  const num = Number(s);
  if (s.length > 0 && !isNaN(num) && isFinite(num) && !/^0\d/.test(s)) return String(num);
  return `'${s.replaceAll("'", "''")}'`;
}

function inferColumns(rows: string[][], hasHeader: boolean): ColumnConfig[] {
  const header = hasHeader ? rows[0] ?? [] : [];
  const maxCols = rows.reduce((max, r) => Math.max(max, r.length), header.length);
  return Array.from({ length: maxCols }, (_, i) => {
    const raw = hasHeader ? header[i] : undefined;
    const name = raw && raw.trim() ? raw.trim() : `column_${i + 1}`;
    return { sourceIndex: i, sourceName: name, targetName: normalizeId(name), include: true };
  });
}

function buildInsertScript(rows: string[][], columns: ColumnConfig[], opts: GeneratorOptions): string {
  const table = normalizeId(opts.tableName);
  if (!table) return '';
  const included = columns.filter(c => c.include && normalizeId(c.targetName));
  if (included.length === 0) return '';

  const filtered = rows.filter(r => r.some(cell => cell !== null && cell !== undefined && String(cell).trim() !== ''));
  if (filtered.length === 0) return '';

  const schema = normalizeId(opts.schemaName);
  const tableRef = schema
    ? `${quoteId(schema, opts.dialect, opts.quoteIdentifiers)}.${quoteId(table, opts.dialect, opts.quoteIdentifiers)}`
    : quoteId(table, opts.dialect, opts.quoteIdentifiers);

  const colList = included.map(c => quoteId(c.targetName, opts.dialect, opts.quoteIdentifiers)).join(', ');
  const rowValues = filtered.map(row => {
    const vals = included.map(c => toSqlLiteral(row[c.sourceIndex] ?? '', opts));
    return `(${vals.join(', ')})`;
  });

  const chunks = chunkArray(rowValues, Math.max(1, opts.rowsPerInsert));
  const stmts = chunks.map(chunk =>
    `INSERT INTO ${tableRef} (${colList})\nVALUES\n${chunk.join(',\n')};`
  );

  return [
    `-- Generated by Kayston's Forge CSV-to-SQL`,
    `-- Dialect: ${opts.dialect} | Rows: ${filtered.length}`,
    '',
    stmts.join('\n\n'),
  ].join('\n');
}

export interface CsvToSqlConfig {
  dialect: SqlDialect;
  tableName: string;
  schemaName: string;
  batchSize: number;
  hasHeader: boolean;
  quoteIdentifiers: boolean;
}

export function parseConfig(raw: string): Partial<CsvToSqlConfig> {
  const cfg: Record<string, string> = {};
  for (const line of raw.split('\n')) {
    const eq = line.indexOf('=');
    if (eq > 0) cfg[line.slice(0, eq).trim().toLowerCase()] = line.slice(eq + 1).trim();
  }
  return {
    tableName: cfg.table || 'my_table',
    schemaName: cfg.schema || '',
    batchSize: parseInt(cfg.batch) > 0 ? parseInt(cfg.batch) : 250,
    hasHeader: cfg.header !== 'false',
    quoteIdentifiers: cfg.quote_identifiers === 'true',
  };
}

function parseCsv(input: string): string[][] {
  const rows: string[][] = [];
  const lines = input.split(/\r?\n/).filter(l => l.trim());
  for (const line of lines) {
    const cells: string[] = [];
    let current = '';
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (inQuote) {
        if (ch === '"' && line[i + 1] === '"') { current += '"'; i++; }
        else if (ch === '"') inQuote = false;
        else current += ch;
      } else {
        if (ch === '"') inQuote = true;
        else if (ch === ',' || ch === '\t') { cells.push(current); current = ''; }
        else current += ch;
      }
    }
    cells.push(current);
    rows.push(cells);
  }
  return rows;
}

export function runCsvToSql(input: string, dialect: SqlDialect, configRaw: string): { output: string; meta: string } {
  const cfg = parseConfig(configRaw);
  const rows = parseCsv(input);
  if (rows.length === 0) return { output: '', meta: 'No data found.' };

  const hasHeader = cfg.hasHeader !== false;
  const columns = inferColumns(rows, hasHeader);
  const dataRows = hasHeader ? rows.slice(1) : rows;

  const opts: GeneratorOptions = {
    dialect,
    tableName: cfg.tableName || 'my_table',
    schemaName: cfg.schemaName || '',
    rowsPerInsert: cfg.batchSize || 250,
    quoteIdentifiers: cfg.quoteIdentifiers || false,
    trimStrings: true,
    emptyStringAsNull: true,
  };

  const sql = buildInsertScript(dataRows, columns, opts);
  if (!sql) return { output: '', meta: 'No valid data rows found.' };

  const meta = `${opts.dialect.toUpperCase()} | Table: ${opts.tableName} | ${dataRows.length} rows | ${columns.length} columns | Batch: ${opts.rowsPerInsert}`;
  return { output: sql, meta };
}
