import {
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowsRightLeftIcon,
  ArrowUturnLeftIcon,
  BeakerIcon,
  CircleStackIcon,
  ClockIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  DocumentTextIcon,
  EyeIcon,
  FingerPrintIcon,
  GlobeAltIcon,
  HashtagIcon,
  KeyIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassCircleIcon,
  MagnifyingGlassIcon,
  PaintBrushIcon,
  PencilSquareIcon,
  PhotoIcon,
  QrCodeIcon,
  ScaleIcon,
  Bars3BottomLeftIcon,
  SparklesIcon,
  TableCellsIcon,
  VariableIcon,
} from '@heroicons/react/24/outline';
import type { ToolDefinition } from '@/types';

export const categoryLabels = {
  encoding: 'Encoding & Encryption',
  escaping: 'Escaping & Entities',
  preview: 'Preview & Comparison',
  format: 'Format Converters',
  beautify: 'Code Beautifiers',
  generator: 'Generators',
  data: 'Data Transformers',
} as const;

export const tools: ToolDefinition[] = [
  { id: 'unix-time-converter', name: 'Unix Time Converter', description: 'Epoch and date conversion', category: 'encoding', icon: ClockIcon, keywords: ['timestamp', 'epoch', 'date'] },
  { id: 'json-format-validate', name: 'JSON Format/Validate', description: 'Validate and format JSON', category: 'encoding', icon: CodeBracketIcon, keywords: ['json', 'validate', 'prettify'] },
  { id: 'base64-string', name: 'Base64 String Encode/Decode', description: 'Encode or decode UTF-8 text', category: 'encoding', icon: HashtagIcon, keywords: ['base64', 'utf8', 'decode'] },
  { id: 'base64-image', name: 'Base64 Image Encode/Decode', description: 'Convert image content and data URLs', category: 'encoding', icon: PhotoIcon, keywords: ['base64', 'image', 'data url'] },
  { id: 'jwt-debugger', name: 'JWT Debugger', description: 'Inspect JWT header and payload', category: 'encoding', icon: KeyIcon, keywords: ['jwt', 'token', 'claims'] },
  { id: 'regexp-tester', name: 'RegExp Tester', description: 'Test regular expressions', category: 'encoding', icon: MagnifyingGlassIcon, keywords: ['regex', 'pattern', 'match'] },
  { id: 'url-encode-decode', name: 'URL Encode/Decode', description: 'Encode and decode URL content', category: 'encoding', icon: LinkIcon, keywords: ['url', 'encode', 'decode'] },
  { id: 'url-parser', name: 'URL Parser', description: 'Break down URL components', category: 'encoding', icon: GlobeAltIcon, keywords: ['url', 'params', 'hostname'] },

  { id: 'html-entity', name: 'HTML Entity Encode/Decode', description: 'Convert text and HTML entities', category: 'escaping', icon: CodeBracketSquareIcon, keywords: ['html', 'entity', 'escape'] },
  { id: 'backslash-escape', name: 'Backslash Escape/Unescape', description: 'Handle escaped string content', category: 'escaping', icon: ArrowUturnLeftIcon, keywords: ['escape', 'unescape', 'unicode'] },
  { id: 'uuid-ulid', name: 'UUID/ULID Generate/Decode', description: 'Generate UUID and ULID values', category: 'escaping', icon: FingerPrintIcon, keywords: ['uuid', 'ulid', 'id'] },

  { id: 'html-preview', name: 'HTML Preview', description: 'Render HTML safely in an iframe', category: 'preview', icon: EyeIcon, keywords: ['html', 'preview', 'iframe'] },
  { id: 'text-diff', name: 'Text Diff Checker', description: 'Compare two text blocks', category: 'preview', icon: ArrowsRightLeftIcon, keywords: ['diff', 'compare', 'patch'] },

  { id: 'yaml-to-json', name: 'YAML to JSON', description: 'Convert YAML documents to JSON', category: 'format', icon: ArrowRightIcon, keywords: ['yaml', 'json', 'convert'] },
  { id: 'json-to-yaml', name: 'JSON to YAML', description: 'Convert JSON documents to YAML', category: 'format', icon: ArrowRightIcon, keywords: ['json', 'yaml', 'convert'] },
  { id: 'number-base', name: 'Number Base Converter', description: 'Convert values across numeric bases', category: 'format', icon: HashtagIcon, keywords: ['binary', 'hex', 'base'] },

  { id: 'html-beautify', name: 'HTML Beautify/Minify', description: 'Format or minify HTML', category: 'beautify', icon: SparklesIcon, keywords: ['html', 'format', 'minify'] },
  { id: 'css-beautify', name: 'CSS Beautify/Minify', description: 'Format or minify CSS', category: 'beautify', icon: PaintBrushIcon, keywords: ['css', 'format', 'minify'] },
  { id: 'js-beautify', name: 'JS Beautify/Minify', description: 'Format or minify JS/TS', category: 'beautify', icon: BeakerIcon, keywords: ['javascript', 'typescript', 'minify'] },
  { id: 'erb-beautify', name: 'ERB Beautify/Minify', description: 'Format ERB templates', category: 'beautify', icon: VariableIcon, keywords: ['erb', 'ruby', 'template'] },
  { id: 'less-beautify', name: 'LESS Beautify/Minify', description: 'Format LESS content', category: 'beautify', icon: PaintBrushIcon, keywords: ['less', 'css'] },
  { id: 'scss-beautify', name: 'SCSS Beautify/Minify', description: 'Format SCSS content', category: 'beautify', icon: PaintBrushIcon, keywords: ['scss', 'sass'] },
  { id: 'xml-beautify', name: 'XML Beautify/Minify', description: 'Format, minify, and validate XML', category: 'beautify', icon: DocumentTextIcon, keywords: ['xml', 'xhtml', 'format'] },

  { id: 'lorem-ipsum', name: 'Lorem Ipsum Generator', description: 'Generate placeholder text', category: 'generator', icon: PencilSquareIcon, keywords: ['lorem', 'placeholder', 'text'] },
  { id: 'qr-code', name: 'QR Code Reader/Generator', description: 'Generate and decode QR codes', category: 'generator', icon: QrCodeIcon, keywords: ['qr', 'barcode', 'scan'] },
  { id: 'string-inspector', name: 'String Inspector', description: 'Inspect text characteristics', category: 'generator', icon: MagnifyingGlassCircleIcon, keywords: ['string', 'unicode', 'bytes'] },

  { id: 'json-to-csv', name: 'JSON to CSV', description: 'Convert JSON arrays to CSV', category: 'data', icon: TableCellsIcon, keywords: ['json', 'csv', 'table'] },
  { id: 'csv-to-json', name: 'CSV to JSON', description: 'Convert CSV to JSON', category: 'data', icon: TableCellsIcon, keywords: ['csv', 'json', 'table'] },
  { id: 'hash-generator', name: 'Hash Generator', description: 'Generate MD5/SHA hashes', category: 'data', icon: LockClosedIcon, keywords: ['hash', 'sha', 'md5'] },
  { id: 'html-to-jsx', name: 'HTML to JSX', description: 'Convert HTML markup to JSX', category: 'data', icon: CodeBracketIcon, keywords: ['html', 'jsx', 'react'] },
  { id: 'markdown-preview', name: 'Markdown Preview', description: 'Render Markdown to HTML', category: 'data', icon: DocumentTextIcon, keywords: ['markdown', 'md', 'preview'] },
  { id: 'sql-formatter', name: 'SQL Formatter', description: 'Format SQL across dialects', category: 'data', icon: CircleStackIcon, keywords: ['sql', 'query', 'formatter'] },
  { id: 'list-splitter', name: 'List Splitter', description: 'Split lists into batches', category: 'data', icon: ListBulletIcon, keywords: ['list', 'split', 'batch', 'chunk'] },
  { id: 'csv-to-sql', name: 'CSV to SQL INSERT', description: 'Generate SQL INSERT from CSV', category: 'data', icon: CircleStackIcon, keywords: ['csv', 'sql', 'insert', 'import'] },
  { id: 'list-compare', name: 'List Compare', description: 'Compare lists, find differences', category: 'data', icon: ScaleIcon, keywords: ['list', 'compare', 'diff', 'venn', 'intersection'] },
  { id: 'text-separator', name: 'Text Separator', description: 'Re-separate text with any delimiter', category: 'data', icon: Bars3BottomLeftIcon, keywords: ['separator', 'delimiter', 'join', 'split', 'comma', 'newline'] },
  // ── New tools ──────────────────────────────────────────────────────────────
  { id: 'string-case', name: 'String Case Converter', description: 'Convert between camelCase, snake_case, etc.', category: 'data', icon: VariableIcon, keywords: ['case', 'camel', 'snake', 'kebab', 'pascal'] },
  { id: 'cron-parser', name: 'Cron Job Parser', description: 'Parse and explain cron expressions', category: 'encoding', icon: ClockIcon, keywords: ['cron', 'schedule', 'job', 'timer'] },
  { id: 'color-converter', name: 'Color Converter', description: 'Convert between HEX, RGB, HSL, HSV', category: 'format', icon: PaintBrushIcon, keywords: ['color', 'hex', 'rgb', 'hsl', 'hsv'] },
  { id: 'php-to-json', name: 'PHP to JSON', description: 'Convert PHP serialized data to JSON', category: 'data', icon: CodeBracketIcon, keywords: ['php', 'serialize', 'json', 'convert'] },
  { id: 'json-to-php', name: 'JSON to PHP', description: 'Convert JSON to PHP array or serialized', category: 'data', icon: CodeBracketIcon, keywords: ['json', 'php', 'array', 'serialize'] },
  { id: 'php-serializer', name: 'PHP Serializer', description: 'Serialize data to PHP format', category: 'data', icon: CodeBracketIcon, keywords: ['php', 'serialize', 'encode'] },
  { id: 'php-unserializer', name: 'PHP Unserializer', description: 'Unserialize PHP data to readable form', category: 'data', icon: CodeBracketIcon, keywords: ['php', 'unserialize', 'decode'] },
  { id: 'random-string', name: 'Random String Generator', description: 'Generate random strings and passphrases', category: 'generator', icon: SparklesIcon, keywords: ['random', 'string', 'password', 'passphrase', 'token'] },
  { id: 'svg-to-css', name: 'SVG to CSS', description: 'Embed SVG as CSS background-image', category: 'format', icon: PaintBrushIcon, keywords: ['svg', 'css', 'background', 'data url'] },
  { id: 'curl-to-code', name: 'cURL to Code', description: 'Convert cURL commands to code', category: 'format', icon: CodeBracketSquareIcon, keywords: ['curl', 'fetch', 'requests', 'http', 'convert'] },
  { id: 'json-to-code', name: 'JSON to Code', description: 'Generate typed structs from JSON', category: 'format', icon: CodeBracketSquareIcon, keywords: ['json', 'typescript', 'python', 'go', 'rust', 'interface', 'struct'] },
  { id: 'cert-decoder', name: 'Certificate Decoder (X.509)', description: 'Decode and inspect X.509 certificates', category: 'encoding', icon: LockClosedIcon, keywords: ['certificate', 'x509', 'ssl', 'tls', 'pem', 'der'] },
  { id: 'hex-to-ascii', name: 'Hex to ASCII', description: 'Convert hex bytes to ASCII text', category: 'format', icon: HashtagIcon, keywords: ['hex', 'ascii', 'decode', 'bytes'] },
  { id: 'ascii-to-hex', name: 'ASCII to Hex', description: 'Convert ASCII text to hex bytes', category: 'format', icon: HashtagIcon, keywords: ['ascii', 'hex', 'encode', 'bytes'] },
  { id: 'line-sort', name: 'Line Sort/Dedupe', description: 'Sort and deduplicate lines of text', category: 'data', icon: Bars3BottomLeftIcon, keywords: ['sort', 'dedupe', 'unique', 'lines', 'text'] },
];

export const defaultToolId = 'json-format-validate';

export const toolMap = new Map(tools.map((tool) => [tool.id, tool]));
